name: "Llama-A100-Distributed"
overwrite: true
data:
  input_file: "train.jsonl"
  # Optional validation file
  validation_file: "val.jsonl"
  # Optional external tokenizer path
  tokenizer_path: "tokenizer"  # Path to a directory containing tokenizer.json
  preprocessing:
    max_context_size: 2048
    chunk_overlap: 128  # Add some overlap for better context learning
    
  tokenizer:
    normal_vocab_size: 256
    special_tokens:
      pad: "<pad>"
      bos: "<bos>"
      eos: "<eos>"
      # Add custom tokens if needed:
      # ctrl1: "<ctrl1>"
      # ctrl2: "<ctrl2>"

model:
  architecture: "llama"
  dimensions:
    hidden_size: 2048
    intermediate_size: 5632  # ~2.75x hidden_size
    num_layers: 24
  attention:
    num_heads: 16
    num_kv_heads: 16
    head_dim: 128  # hidden_size / num_heads
    max_position_embeddings: 4096
  normalization:
    rms_norm_eps: 1.0e-5
  rope:
    theta: 10000
    traditional: false
    scaling: null
  misc:
    attention_bias: false
    mlp_bias: false
    tie_word_embeddings: true

training:
  # Number of epochs to train for (optional)
  epochs: 1
  hyperparameters:
    batch_size: 64  # Increased batch size for A100s
    learning_rate: 3.0e-4
    weight_decay: 0.1
    gradient_clip: 1.0  # Added gradient clipping
    
  scheduler:
    type: "cosine_with_warmup"  # Add warmup for stability
    min_lr_ratio: 0.1  # Minimum LR as a ratio of initial LR
    warmup_steps: 2000
    
  optimization:
    optimizer: "adamw"  # Use AdamW for stability
    betas: [0.9, 0.95]
    eps: 1.0e-8

logging:
  log_dir: "logs"
  checkpoint_dir: "checkpoints"
  steps:
    logging_interval: 10
    checkpoint_interval: 5000
    validation_interval: 1000  # Run validation every 1000 steps
  metrics:
    log_loss: true
    log_perplexity: true
    log_tokens_per_second: true
    log_learning_rate: true
    log_tokens_processed: true

system:
  seed: 42
  device: "gpu"
  distributed: true  # Enable distributed training
  devices: []  # No MLX devices when using pure CUDA
  cuda_devices: [0, 1]  # Using both A100 GPUs