name: "MLX-80M-FineWeb-Stream"
overwrite: true
data:
  input_file: "train.jsonl"
  validation_file: "val.jsonl"
  tokenizer_path: "tokenizer"
  preprocessing:
    max_context_size: 2048
    chunk_overlap: 128
    
  tokenizer:
    normal_vocab_size: 32000
    special_tokens:
      pad: "<pad>"
      bos: "<bos>"
      eos: "<eos>"

model:
  architecture: "llama"
  dimensions:
    hidden_size: 1024
    intermediate_size: 2816
    num_layers: 12
  attention:
    num_heads: 16
    num_kv_heads: 8
    head_dim: 64
    max_position_embeddings: 4096
    use_flash_attention: true
  normalization:
    rms_norm_eps: 1.0e-5
  rope:
    theta: 10000
    traditional: false
    scaling: null
  misc:
    attention_bias: false
    mlp_bias: false
    tie_word_embeddings: true

training:
  epochs: null
  hyperparameters:
    batch_size: 4
    gradient_accumulation_steps: 16
    learning_rate: 3.0e-4
    weight_decay: 0.01
    iters: 10000
    
  scheduler:
    type: "cosine_with_warmup"
    min_lr_ratio: 0.1
    warmup_steps: 1000
    
  optimization:
    optimizer: "muon"
    betas: [0.9, 0.95]
    eps: 1.0e-8

logging:
  log_dir: "logs"
  checkpoint_dir: "checkpoints/80m-fineweb"
  steps:
    logging_interval: 10
    checkpoint_interval: 500
    validation_interval: 100
  metrics:
    log_loss: true
    log_perplexity: true
    log_tokens_per_second: true
    log_learning_rate: true
    log_tokens_processed: true

system:
  seed: 42
  device: "gpu"
  distributed: false
  devices: ["mlx"]
  memory_limit: 30