name: "Llama-256M-Distributed"
overwrite: true
data:
  input_file: "train.jsonl"
  validation_file: "val.jsonl"
  tokenizer_path: "tokenizer"
  preprocessing:
    max_context_size: 2048
    chunk_overlap: 128
    
  tokenizer:
    normal_vocab_size: 256
    special_tokens:
      pad: "<pad>"
      bos: "<bos>"
      eos: "<eos>"

model:
  architecture: "llama"
  dimensions:
    hidden_size: 1024
    intermediate_size: 2816  # ~2.75x hidden_size
    num_layers: 16
  attention:
    num_heads: 16
    num_kv_heads: 16
    head_dim: 64  # hidden_size / num_heads
    max_position_embeddings: 4096
  normalization:
    rms_norm_eps: 1.0e-5
  rope:
    theta: 10000
    traditional: false
    scaling: null
  misc:
    attention_bias: false
    mlp_bias: false
    tie_word_embeddings: true

training:
  epochs: 1
  hyperparameters:
    batch_size: 64
    learning_rate: 3.0e-4
    weight_decay: 0.1
    gradient_clip: 1.0
    
  scheduler:
    type: "cosine_with_warmup"
    min_lr_ratio: 0.1
    warmup_steps: 2000
    
  optimization:
    optimizer: "adamw"
    betas: [0.9, 0.95]
    eps: 1.0e-8

logging:
  log_dir: "logs"
  checkpoint_dir: "checkpoints"
  steps:
    logging_interval: 10
    checkpoint_interval: 2000
    validation_interval: 500
  metrics:
    log_loss: true
    log_perplexity: true
    log_tokens_per_second: true
    log_learning_rate: true
    log_tokens_processed: true

system:
  seed: 42
  device: "gpu"
  distributed: true
  devices: []
  cuda_devices: [0, 1]  # Using both A100 GPUs