name: "Llama (650M)"
overwrite: true
data:
  input_file: "train.jsonl"
  # Optional validation file
  validation_file: "val.jsonl"
  # Optional external tokenizer path
  tokenizer_path: "tokenizer"  # Path to a directory containing tokenizer.json
  preprocessing:
    max_context_size: 2048
    chunk_overlap: 0  # If > 0, chunks will overlap by this many tokens
    
  tokenizer:
    normal_vocab_size: 32000
    special_tokens:
      pad: "<pad>"
      bos: "<bos>"
      eos: "<eos>"

model:
  architecture: "llama"
  dimensions:
    hidden_size: 1024
    intermediate_size: 2816  # ~2.75x hidden_size
    num_layers: 24
  attention:
    num_heads: 16
    num_kv_heads: null  # If null, equals num_heads
    head_dim: null  # If null, computed from hidden_size/num_heads
    max_position_embeddings: 2048
  normalization:
    rms_norm_eps: 1.0e-5
  rope:
    theta: 10000
    traditional: false
    scaling: null
  misc:
    attention_bias: false
    mlp_bias: false
    tie_word_embeddings: true

training:
  epochs: 3
  hyperparameters:
    batch_size: 32
    learning_rate: 3.0e-4
    weight_decay: 0.1
    
  scheduler:
    type: "cosine_with_warmup"
    min_lr_ratio: 0.1
    warmup_steps: 3000
    
  optimization:
    optimizer: "muon"

logging:
  log_dir: "logs"
  checkpoint_dir: "checkpoints"
  steps:
    logging_interval: 10
    checkpoint_interval: 1000
    validation_interval: 500
  metrics:
    log_loss: true
    log_perplexity: true
    log_tokens_per_second: true
    log_learning_rate: true
    log_tokens_processed: true

system:
  seed: 42
  device: "gpu"
  distributed: true
  devices: ["gpu", "cpu"]
  cuda_devices: null