name: "TinyStories-40M-demo"
overwrite: true

data:
  input_file: "processed_tinystories/train.jsonl"
  validation_file: "processed_tinystories/val.jsonl"
  tokenizer_path: "processed_tinystories/tokenizer"
  preprocessing:
    max_context_size: 512
    chunk_overlap: 64
  tokenizer:
    normal_vocab_size: 8000
    special_tokens:
      pad: "<pad>"
      bos: "<bos>"
      eos: "<eos>"

model:
  architecture: "llama"
  dimensions:
    hidden_size: 512
    intermediate_size: 2048
    num_layers: 8
  attention:
    num_heads: 8
    num_kv_heads: 8
    head_dim: 64
    max_position_embeddings: 512
  normalization:
    rms_norm_eps: 1.0e-5
  rope:
    theta: 10000
    traditional: false
    scaling: null
  misc:
    attention_bias: false
    mlp_bias: false
    tie_word_embeddings: true

training:
  epochs: 3
  hyperparameters:
    batch_size: 16
    gradient_accumulation_steps: 1
    learning_rate: 6e-4
    weight_decay: 0.01
    gradient_clip: 1.0
    iters: 5000
  scheduler:
    type: "cosine_with_warmup"
    min_lr_ratio: 0.1
    warmup_steps: 200
  optimization:
    optimizer: "adamw"
    betas: [0.9, 0.95]
    eps: 1e-8

logging:
  log_dir: "runs/TinyStories-40M-demo/logs"
  checkpoint_dir: "runs/TinyStories-40M-demo/checkpoints"
  steps:
    logging_interval: 100
    checkpoint_interval: 500
    validation_interval: 200
  metrics:
    log_loss: true
    log_perplexity: true
    log_tokens_per_second: true
    log_learning_rate: true
    log_tokens_processed: true

system:
  seed: 42
  device: "gpu"
  distributed: false
  devices: ["mlx"]
  cuda_devices: []

resume: null