name: "40m-finetune"
overwrite: true
data:
  input_file: "train.jsonl"
  validation_file: "val.jsonl"
  tokenizer_path: "tokenizer"
  preprocessing:
    max_context_size: 1024
    chunk_overlap: 64
    
  tokenizer:
    normal_vocab_size: 32000
    special_tokens:
      pad: "<pad>"
      bos: "<bos>"
      eos: "<eos>"

model:
  architecture: "llama"
  dimensions:
    hidden_size: 768
    intermediate_size: 1536
    num_layers: 6
  attention:
    num_heads: 12
    num_kv_heads: 6
    head_dim: 64
    max_position_embeddings: 4096
  normalization:
    rms_norm_eps: 1.0e-5
  rope:
    theta: 10000
    traditional: false
    scaling: null
  misc:
    attention_bias: false
    mlp_bias: false
    tie_word_embeddings: true
    use_flash_attention: false

training:
  epochs: 30
  hyperparameters:
    batch_size: 64
    learning_rate: 9.0e-3
    weight_decay: 0.01
    iters: 5000
    
  scheduler:
    type: "cosine_with_warmup"
    min_lr_ratio: 0.03
    warmup_steps: 500
    
  optimization:
    optimizer: "muon"

logging:
  log_dir: "logs"
  checkpoint_dir: "checkpoints"
  steps:
    logging_interval: 10
    checkpoint_interval: 500
    validation_interval: 100
  metrics:
    log_loss: true
    log_perplexity: true
    log_tokens_per_second: true
    log_learning_rate: true
    log_tokens_processed: true

system:
  seed: 42
  device: "gpu"
  distributed: false
  devices: ["mlx"]
resume:
  checkpoint: "runs/Muon-40M/checkpoints/step_final"
  reset_optimizer: true
  reset_training_state: true
