name: "Test-Model-20250425_234526"
overwrite: true
data:
  input_file: "train.jsonl"
  validation_file: "val.jsonl"
  tokenizer_path: "tokenizer"
  preprocessing:
    max_context_size: 128  # Very small context for testing
    chunk_overlap: 16
    
  tokenizer:
    normal_vocab_size: 32000
    special_tokens:
      pad: "<pad>"
      bos: "<bos>"
      eos: "<eos>"

model:
  architecture: "llama"
  dimensions:
    hidden_size: 128
    intermediate_size: 256
    num_layers: 2
  attention:
    num_heads: 4
    num_kv_heads: 4  # No GQA for testing
    head_dim: 32
    max_position_embeddings: 128
    use_flash_attention: false  # Disable flash attention
  normalization:
    rms_norm_eps: 1.0e-5
  rope:
    theta: 10000
    traditional: false
    scaling: null
  misc:
    attention_bias: false
    mlp_bias: false
    tie_word_embeddings: true

training:
  epochs: null
  hyperparameters:
    batch_size: 8  # Small batch size
    gradient_accumulation_steps: 1  # No accumulation
    learning_rate: 3.0e-3
    weight_decay: 0.01
    gradient_clip: 1.0
    iters: 10  # Just a few iterations to test
    
  scheduler:
    type: "cosine_with_warmup"
    min_lr_ratio: 0.1
    warmup_steps: 2
    
  optimization:
    optimizer: "adamw"  # Use AdamW for simplicity
    betas: [0.9, 0.999]
    eps: 1.0e-8

logging:
  log_dir: "logs"
  checkpoint_dir: "checkpoints/test"
  steps:
    logging_interval: 1
    checkpoint_interval: 5
    validation_interval: 5
  metrics:
    log_loss: true
    log_perplexity: true
    log_tokens_per_second: true
    log_learning_rate: true
    log_tokens_processed: true

system:
  seed: 42
  device: "gpu"
  distributed: false
  devices: ["mlx"]
  cuda_devices: []
