name: "Llama-87M-1B"
overwrite: true
data:
  input_file: "processed_dataset/train.jsonl"
  validation_file: "processed_dataset/val.jsonl"
  tokenizer_path: "tokenizer"
  preprocessing:
    max_context_size: 2048
    chunk_overlap: 64
  tokenizer:
    normal_vocab_size: 32000
    special_tokens:
      pad: "<pad>"
      bos: "<bos>"
      eos: "<eos>"
model:
  architecture: "llama"
  dimensions:
    hidden_size: 1024
    intermediate_size: 2816
    num_layers: 12
  attention:
    num_heads: 16
    num_kv_heads: 8
    head_dim: 64
    max_position_embeddings: 2048
    use_flash_attention: true
    # Enable FlexAttention implementation for more flexible and potentially faster attention patterns
    use_flex_attention: true
  normalization:
    rms_norm_eps: 1.0e-5
  rope:
    theta: 10000
    traditional: false
    scaling: null
  misc:
    attention_bias: false
    mlp_bias: false
    tie_word_embeddings: true
training:
  epochs: null
  hyperparameters:
    batch_size: 8
    gradient_accumulation_steps: 8
    learning_rate: 1.0e-3
    weight_decay: 0.1
    gradient_clip: 1.0
    iters: 7629
  scheduler:
    type: "cosine_with_warmup"
    min_lr_ratio: 0.06
    warmup_steps: 500
  optimization:
    optimizer: "muon"
    betas: [0.9, 0.95]
    eps: 1.0e-8
logging:
  log_dir: "logs"
  checkpoint_dir: "checkpoints/llama-87m-1B"
  steps:
    logging_interval: 10
    checkpoint_interval: 200
    validation_interval: 100
  metrics:
    log_loss: true
    log_perplexity: true
    log_tokens_per_second: true
    log_learning_rate: true
    log_tokens_processed: true
system:
  seed: 42
  device: "gpu"
  distributed: false
  devices: ["gpu"]