name: "Fast-124M"
overwrite: true
data:
  input_file: "train.jsonl"
  validation_file: "val.jsonl"
  tokenizer_path: "tokenizer"
  preprocessing:
    max_context_size: 512
    chunk_overlap: 32
    
  tokenizer:
    normal_vocab_size: 32000
    special_tokens:
      pad: "<pad>"
      bos: "<bos>"
      eos: "<eos>"

model:
  architecture: "llama"
  dimensions:
    hidden_size: 768
    intermediate_size: 2048
    num_layers: 16
  attention:
    num_heads: 12
    num_kv_heads: 6
    head_dim: 64
    max_position_embeddings: 1024
    use_flash_attention: true
    flash_block_size: 64
  normalization:
    rms_norm_eps: 1.0e-5
  rope:
    theta: 10000
    traditional: false
    scaling: null
  misc:
    attention_bias: false
    mlp_bias: false
    tie_word_embeddings: true

training:
  epochs: null
  hyperparameters:
    batch_size: 32
    gradient_accumulation_steps: 1
    learning_rate: 6.0e-4
    weight_decay: 0.01
    gradient_clip: 1.0
    iters: 100
    
  scheduler:
    type: "cosine_with_warmup"
    min_lr_ratio: 0.1
    warmup_steps: 20
    
  optimization:
    optimizer: "adamw"
    betas: [0.9, 0.95]
    eps: 1.0e-8

logging:
  log_dir: "logs"
  checkpoint_dir: "checkpoints/fast-124m"
  steps:
    logging_interval: 5
    checkpoint_interval: 50
    validation_interval: 25
  metrics:
    log_loss: true
    log_perplexity: true
    log_tokens_per_second: true
    log_learning_rate: true
    log_tokens_processed: true

system:
  seed: 42
  device: "gpu"
  distributed: false
  devices: ["gpu"]
  memory_limit: 32768